name: "kanban_services"

services:
  postgres_cluster:
    image: postgres:15
    container_name: kanban_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_cluster_data:/var/lib/postgresql/data
      - ./infrastructure/postgres/init-dbs.sql:/docker-entrypoint-initdb.d/init-dbs.sql
    restart: always

volumes:
  postgres_cluster_data:
