name: "kanban_db"

services:
  auth_db:
    image: postgres:15
    container_name: auth_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data

  noti_db:
    image: postgres:15
    container_name: noti_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: noti_db
    ports:
      - "5434:5432"
    volumes:
      - noti_data:/var/lib/postgresql/data

  board_db:
    image: postgres:15
    container_name: board_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: board_db
    ports:
      - "5435:5432"
    volumes:
      - board_data:/var/lib/postgresql/data

volumes:
  auth_data:
  noti_data:
  board_data:
